[package]
name = "namigator-sys"
version = "0.1.0"
edition = "2021"

links = "namigator"

exclude = ["vendor/namigator/test", ".git"]

[build-dependencies]
cc = {version = "1.0.73", features = ["parallel"]}
